[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"

[theme]
base = "light"
primaryColor = "#19736b"
backgroundColor = "#f8faf9"
secondaryBackgroundColor = "#edf2f0"
textColor = "#182e2b"
